# Generated by Django 5.2.9 on 2025-12-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
