# Generated by Django 5.2.9 on 2025-12-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_aboutme_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
    ]
